# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Marla & Jay"
subtitle: "July 21, 2018"
email: zeschinwedding@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  We're getting married!
url: "http://jayandmarla.com"
baseurl: ""
plugins:
  - jekyll-seo-tag
collections:
- sections
google_analytics: "UA-7482331-2"
